import Head from "next/head";

import { Footer, Navbar } from "../components/common";
import { Container } from "../components/ui";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Meteo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Container>
        <main className={styles.main}>Hello enter the name of the city</main>
      </Container>
      <Footer />
    </div>
  );
}
