import Head from "next/head";

import { Footer, Layout, Navbar } from "../components/common";
import { Container } from "../components/ui";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Meteo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Hello enter the name of the city
    </div>
  );
}
Home.Layout = Layout;
